# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\tinference\"\x1e\n\x0ePredictRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"I\n\x0fPredictResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0e\n\x06rating\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"w\n\x0eHealthResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .inference.HealthResponse.Status\"3\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SERVING\x10\x01\x12\x0f\n\x0bNOT_SERVING\x10\x02\x32\x97\x01\n\x10InferenceService\x12\x42\n\x07Predict\x12\x19.inference.PredictRequest\x1a\x1a.inference.PredictResponse\"\x00\x12?\n\x06Health\x12\x18.inference.HealthRequest\x1a\x19.inference.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTREQUEST']._serialized_start=30
  _globals['_PREDICTREQUEST']._serialized_end=60
  _globals['_PREDICTRESPONSE']._serialized_start=62
  _globals['_PREDICTRESPONSE']._serialized_end=135
  _globals['_HEALTHREQUEST']._serialized_start=137
  _globals['_HEALTHREQUEST']._serialized_end=152
  _globals['_HEALTHRESPONSE']._serialized_start=154
  _globals['_HEALTHRESPONSE']._serialized_end=273
  _globals['_HEALTHRESPONSE_STATUS']._serialized_start=222
  _globals['_HEALTHRESPONSE_STATUS']._serialized_end=273
  _globals['_INFERENCESERVICE']._serialized_start=276
  _globals['_INFERENCESERVICE']._serialized_end=427
# @@protoc_insertion_point(module_scope)
