apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql-container
        image: filipstrozik/lsdp:latest
        envFrom:
        - configMapRef:
            name: {{ include "polwro.fullname" $ }}-env
        ports:
        - containerPort: 5000
        command: ["python", "graphql_service/app.py"]

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  selector:
    app: graphql
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
---